Solve the "AttributeError: module 'numpy' has no attribute 'bool8'. Did you mean: 'bool'?" problem caused by the high version of numpy  and Solve the problem caused by the change of the default value of the weights_only parameter in PyTorch 2.6 version